mod: Dockerfile has been modified

diff --git a/.github/workflows/my_cppaction.yml b/.github/workflows/my_cppaction.yml
--- a/.github/workflows/my_cppaction.yml
+++ b/.github/workflows/my_cppaction.yml
@@ -23,27 +23,21 @@ jobs:
         run: |
           clang-tidy srcTMP/*.cpp -- -Iinclude
 
-    # - name: check compilation
-    #   run: |
-    #       echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
-    #       {
-    #         set +e
-    #         make ADDITIONAL_FLAGS="-Werror"
-    #         if [ $? -ne 0 ]; then
-    #           echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
-    #           echo "Compilation failed."
-    #           exit 1
-    #         else
-    #           echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
-    #           exit 0
-    #         fi
-    #       }
-
-    # - name: install clang-tidy
-    #   run: sudo dnf install -y clang-tools-extra
-
-    # - name: install bear
-    #   run: sudo dnf install -y bear
+      - name: check compilation
+        run: |
+            echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
+            {
+              set +e
+              make ADDITIONAL_FLAGS="-Werror"
+              if [ $? -ne 0 ]; then
+                echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
+                echo "Compilation failed."
+                exit 1
+              else
+                echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
+                exit 0
+              fi
+            }
 
     # - name: code analyse
     #   run: |
