mod: remove check of the compilation to only see if the code analyse actually works without pre-install on the action

diff --git a/.github/workflows/my_cppaction.yml b/.github/workflows/my_cppaction.yml
--- a/.github/workflows/my_cppaction.yml
+++ b/.github/workflows/my_cppaction.yml
@@ -19,21 +19,21 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: check compilation
-      run: |
-          echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
-          {
-            set +e
-            make ADDITIONAL_FLAGS="-Werror"
-            if [ $? -ne 0 ]; then
-              echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
-              echo "Compilation failed."
-              exit 1
-            else
-              echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
-              exit 0
-            fi
-          }
+    # - name: check compilation
+    #   run: |
+    #       echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
+    #       {
+    #         set +e
+    #         make ADDITIONAL_FLAGS="-Werror"
+    #         if [ $? -ne 0 ]; then
+    #           echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
+    #           echo "Compilation failed."
+    #           exit 1
+    #         else
+    #           echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
+    #           exit 0
+    #         fi
+    #       }
 
     # - name: install clang-tidy
     #   run: sudo dnf install -y clang-tools-extra
